ftp:

flowcell:

workbatch:

base_path:

batch_id:

reference_genome:
  /mnt/Data1/resources/human_g1k_v37.fasta
tempfolder:
  /mnt/Data1/targeted_sequencing/tmp
bwa:
  /usr/share/bwa/bwa-0.7.15/bwa
java:
  /usr/share/java-1.8.0/jdk1.8.0_92/bin/java
picard:
  /usr/share/picard/picard-tools-2.5.0/picard.jar
gatk:
  /usr/share/gatk/GenomeAnalysisTK-3.7.0/GenomeAnalysisTK.jar
python:
  /usr/share/Python-3.5.1/python  
known_indels:
  /mnt/Data1/resources/Mills_and_1000G_gold_standard.indels.b37.vcf
rscript:
  /usr/share/r/R-3.2.0/bin/Rscript
common:
  /mnt/Data1/resources/common_no_known_medical_impact_20160302-edited.vcf
artefacts:
  /mnt/Data1/resources/common_artefacts/V501_19052014_common_artefacts.vcf
alamut:
  /mnt/Data3/alamut-batch-1.5.2/alamut-batch  
verifybamid:
  /mnt/Data1/resources/clean_call_data
dbsnp_path:
  /mnt/Data1/resources/dbsnp_137.b37.vcf
ndm_snps_path:
  /mnt/Data1/targeted_sequencing/intervals/general/6q24_SNPs.interval_list
type_one_snps_path:
  /mnt/Data1/targeted_sequencing/intervals/general/type_one_SNPs.interval_list
phenotype_metric_line: 
  8
overall_metric_line: 
  8
duplicate_metric_line: 
  7
hgmduser:
  rdemolgen
hgmdpass:
  rdemolgen
sample_list_path:
  sample_list_all.csv
panels:
  v5:
    panel_id: v5
    panel_version: V5
    variants_directory: variants/haplotyper
    intervals_directory: intervals/v5/grch-37
    transcript_file_path: intervals/v5/grch-37/v5_transcripts.yaml
    unwanted_file_path: variants_regions_to_dismiss/unwanted_variants.csv
    wanted_file_path: variants_regions_to_process/wanted_regions.csv
    coverage_cutoff: 30
    allowed_genesets:
      NDM,
      MODY,
      HI,
      NDM_MODY,
      AUTOIMMUNE,
      ALL_V5
  v501:
    panel_id: v501
    panel_version: V501
    variants_directory: variants/haplotyper
    intervals_directory: intervals/v501/grch-37
    transcript_file_path: intervals/v501/grch-37/v501_transcripts.yaml
    unwanted_file_path: variants_regions_to_dismiss/unwanted_variants.csv
    wanted_file_path: variants_regions_to_process/wanted_regions.csv
    coverage_cutoff: 30
    allowed_genesets:
      NDM,
      MODY,
      HI,
      NDM_MODY,
      AUTOIMMUNE,
      ALL_V501
  v603:
    panel_id: v603
    panel_version: V603
    variants_directory: variants/haplotyper
    intervals_directory: intervals/v603/grch-37
    transcript_file_path: intervals/v603/grch-37/v603_transcripts.yaml
    unwanted_file_path: variants_regions_to_dismiss/unwanted_variants.csv
    wanted_file_path: variants_regions_to_process/wanted_regions.csv
    coverage_cutoff: 30
    allowed_genesets:
      AARSKOG,
      ACRO,
      ALAGILLE,
      ALDH7A1,
      ALL_V603,
      BANF1,
      CARNEY,
      CDP,
      CGL,
      CH,
      CHILD,
      CHOREA,
      CPHD,
      DCM_LMNA,
      EXOSTOSIS,
      EYE,
      FEINGOLD,
      FGD,
      FHH,
      FHH_FIH,
      FIH,
      FOXF1,
      FPL,
      FTC,
      GACI,
      GASTRO,
      HIRSCHSPRUNG,
      HPE,
      HTX,
      HYPO_PTH,
      IGHD,
      KALLMAN,
      MFDM,
      MOBIUS,
      NEOPLASIA,
      NOTCH1,
      NOTCH2,
      NOTCH3,
      PCH,
      PDE4D,
      PHA,
      PHAEO,
      PIK3R1,
      POREN,
      PPNAD,
      PRKAR1A,
      RET,
      RICKETS, 
      SCD,
      SLC2A2,
      THR,
      TRAP1,
      VHL,
      WRN,
      ZMPSTE24
samples:
  #format sample_name: [<forward_fastq>, <reverse_fastq>, <gender>, <library>, <panel>]  
